# Generated by Django 3.0.7 on 2020-06-25 22:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('version', models.CharField(default='v0.0.0', help_text='Version must follow semantic versioning pattern (e.g.: v0.0.0)', max_length=12)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('source', models.URLField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisation', models.CharField(max_length=100)),
                ('manager_join_token', models.CharField(editable=False, max_length=86)),
                ('worker_join_token', models.CharField(editable=False, max_length=86)),
                ('base_url', models.URLField(default='https://localhost:4433')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docker_url', models.URLField()),
                ('swarm_manager', models.BooleanField()),
                ('hostname', models.CharField(max_length=100)),
                ('swarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', related_query_name='node', to='rest_api.Swarm')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='rest_api.Service')),
                ('swarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='rest_api.Swarm')),
            ],
        ),
    ]
